apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-app
  labels:
    app: order-app
    group: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-app
  template:
    metadata:
      labels:
        app: order-app
        group: backend
    spec:
      containers:
        - name: order-app
          image: faridul/so-app:latest
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: postgres-config-order
          env:
            - name: PAYMENT_SERVICE_URL
              value: http://payment-app:4001
            - name: NODE_ENV
              value: production
            - name: DATABASE_URL
              value: postgres://setel:setel@postgres-order:5432/setel