apiVersion: v1
kind: Service
metadata:
  name: postgres-order
  labels: 
    group: db
spec:
  type: ClusterIP
  selector:             
    app: postgres-order
  ports:
    - port: 5432  
      targetPort: 5432 
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-payment
  labels: 
    group: db
spec:
  type: ClusterIP
  selector:             
    app: postgres-payment
  ports:
    - port: 5432  
      targetPort: 5432 